#!/bin/bash
#
# Perform necessary turbot-client setup steps
# after package is installed.
#

PROGNAME=$(basename $0)
DEST_DIR=/opt/turbot-client

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

ln -sf $DEST_DIR/bin/turbot /usr/bin/turbot || error_exit "Cannot link turbot to /usr/bin"
echo "Thank you for installing turbot!"

exit 0
