#!/bin/bash
#
# Perform necessary turbot-client setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}
rm /usr/bin/turbot || error_exit "Cannot unlink turbot from /usr/bin"
exit 0
