driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/turbot-client']

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-14.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-13.04
    run_list: apt::default
  - name: ubuntu-12.10
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-11.04
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/turbot-client
        install_dir: /opt/turbot-client
